# The current version of the config schema
version: 1
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: nvim
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". If blank, will refer to environment. Set the value to "cat" to disable the pager.
pager: less
# Aliases allow you to create nicknames for gh commands
aliases:
  co: pr checkout
  il: issue list -L 1000
  issue search: '!$HOME/.config/scripts/gh_issue_search'
  project add: '!$HOME/.config/scripts/gh_project_add'
  project status: '!$HOME/.config/scripts/gh_project_status'
  collaborators: '!$HOME/.config/scripts/gh_collaborators'
  team: '!$HOME/.config/scripts/gh_collaborators'
  issue worktree: '!$HOME/.config/scripts/gh_issue_worktree_develop "$@"'
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser: /usr/bin/firefox
